import type { Service } from './types';


export const SERVICES: Service[] = [
  {
    id: '1',
    title: 'Tractor Rental',
    description: 'High-quality tractor available for rent with experienced operator',
    provider: 'Ramesh Kumar',
    rating: 4.8,
    price: 700,
    category: 'equipment',
    image: 'https://picsum.photos/seed/tractor/300/200',
  },
  {
    id: '2',
    title: 'Harvesting Labor',
    description: 'Skilled labor team for efficient crop harvesting services',
    provider: 'Sita Devi & Group',
    rating: 4.9,
    price: 400,
    category: 'labor',
    image: 'https://picsum.photos/seed/harvest/300/200',
  },
  {
    id: '3',
    title: 'Seed & Fertilizer Supply',
    description: 'Premium quality seeds and organic fertilizers for better yield',
    provider: 'Gupta Traders',
    rating: 4.5,
    price: 0,
    category: 'supplies',
    image: 'https://picsum.photos/seed/fertilizer/300/200',
  },
  {
    id: '4',
    title: 'Crop Transportation',
    description: 'Reliable transportation service for your agricultural produce',
    provider: 'Singh Logistics',
    rating: 4.7,
    price: 20,
    category: 'transport',
    image: 'https://picsum.photos/seed/truck/300/200',
  },
  // Added more services for farmers across categories
  {
    id: '5',
    title: 'Soil Testing Service',
    description: 'On-site soil sampling with detailed nutrient analysis and recommendations',
    provider: 'AgriLabs India',
    rating: 4.6,
    price: 599,
    category: 'soil',
    image: 'https://www.google.com/imgres?q=soil&imgurl=https%3A%2F%2Fwww.eurokidsindia.com%2Fblog%2Fwp-content%2Fuploads%2F2023%2F11%2Fdifferent-types-of-soils-and-their-charachterstics-870x570.jpg&imgrefurl=https%3A%2F%2Fwww.eurokidsindia.com%2Fblog%2Fwhat-are-different-types-of-soils-and-their-characteristics.php&docid=Wdgsho6NizRx5M&tbnid=KIvofS63WX62PM&vet=12ahUKEwijha256cqPAxVR1TgGHSsPE8EQM3oECBMQAA..i&w=870&h=570&hcb=2&ved=2ahUKEwijha256cqPAxVR1TgGHSsPE8EQM3oECBMQAA',
  },
  {
    id: '6',
    title: 'Drip Irrigation Setup',
    description: 'Design and installation of water-efficient drip irrigation systems',
    provider: 'Jal Seva Irrigation',
    rating: 4.7,
    price: 2500,
    category: 'irrigation',
    image: 'https://picsum.photos/seed/drip/300/200',
  },
  {
    id: '7',
    title: 'Pest Control (Organic)',
    description: 'Eco-friendly pest management using organic sprays and traps',
    provider: 'GreenShield',
    rating: 4.4,
    price: 499,
    category: 'advisory',
    image: 'https://picsum.photos/seed/pest/300/200',
  },
  {
    id: '8',
    title: 'Cold Storage Rental',
    description: 'Short-term cold storage to reduce post-harvest loss',
    provider: 'FreshKeep Warehouses',
    rating: 4.3,
    price: 1500,
    category: 'storage',
    image: 'https://picsum.photos/seed/coldstorage/300/200',
  },
  {
    id: '9',
    title: 'Agri-Drone Spraying',
    description: 'Precision spraying service using drones for uniform coverage',
    provider: 'SkyFarm Tech',
    rating: 4.5,
    price: 1200,
    category: 'drone',
    image: 'https://picsum.photos/seed/drone/300/200',
  },
  {
    id: '10',
    title: 'Seed Treatment',
    description: 'Professional seed treatment service to improve germination and vigor',
    provider: 'Bharat Krishi Kendra',
    rating: 4.2,
    price: 199,
    category: 'seeds',
    image: 'https://picsum.photos/seed/seed/300/200',
  },
  {
    id: '11',
    title: 'Market Linkage',
    description: 'Connect directly with buyers and mandis for better prices',
    provider: 'Kisan Connect',
    rating: 4.1,
    price: 0,
    category: 'market',
    image: 'https://picsum.photos/seed/market/300/200',
  },
  {
    id: '12',
    title: 'Crop Insurance Assistance',
    description: 'Help with crop insurance enrollment and claims support',
    provider: 'Suraksha Insure',
    rating: 4.0,
    price: 0,
    category: 'insurance',
    image: 'https://picsum.photos/seed/insurance/300/200',
  },
  {
    id: '13',
    title: 'Agro Credit Facilitation',
    description: 'Assistance in applying for low-interest agricultural loans',
    provider: 'Grameen Finance',
    rating: 4.2,
    price: 0,
    category: 'credit',
    image: 'https://picsum.photos/seed/credit/300/200',
  },
  {
    id: '14',
    title: 'Farmer Training Workshop',
    description: 'One-day training on modern cultivation and water-saving practices',
    provider: 'Krishi Vigyan Kendra',
    rating: 4.6,
    price: 99,
    category: 'training',
    image: 'https://picsum.photos/seed/training/300/200',
  },
];
